# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableCoffee = QtWidgets.QTableWidget(self.centralwidget)
        self.tableCoffee.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCoffee.setObjectName("tableCoffee")
        self.tableCoffee.setColumnCount(0)
        self.tableCoffee.setRowCount(0)
        self.verticalLayout.addWidget(self.tableCoffee)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAddEdit = QtWidgets.QAction(MainWindow)
        self.actionAddEdit.setObjectName("actionAddEdit")
        self.menu.addAction(self.actionAddEdit)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "КофеТека"))
        self.menu.setTitle(_translate("MainWindow", "Добавить/Изменить"))
        self.actionAddEdit.setText(_translate("MainWindow", "Добавить/Изменить"))
